=== maximka76667/xml-peliculas/peliculas.dtd
<!ELEMENT peliculas (pelicula)+>
<!ELEMENT pelicula (titulo,duracion, director+, actor+, guionista*, productora*, sinopsis?,recaudacion?)>
  <!ATTLIST pelicula 
                  tipo (drama | comedia | aventura | sci-fi | western | misterio | horror | romance | documental) #IMPLIED
                  clasificacion ( NO7 | NO12 | NO16 | NO18 | X | TP ) "TP"
                  puntuacion (1 | 2 | 3 | 4 | 5)  #REQUIRED
                  anho CDATA #IMPLIED>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT duracion (#PCDATA)>
<!ELEMENT director (#PCDATA)>
<!ELEMENT actor (#PCDATA)>
<!ELEMENT guionista (#PCDATA)>
<!ELEMENT productora (#PCDATA)>
<!ELEMENT sinopsis (#PCDATA)>
<!ELEMENT recaudacion EMPTY>
    <!ATTLIST recaudacion
                      euros CDATA #REQUIRED>

=== maximka76667/xml-peliculas/peliculas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE peliculas SYSTEM "peliculas.dtd">
<peliculas>
    <pelicula puntuacion="4">
        <titulo>The Batman</titulo>
        <duracion>2h 56min</duracion>
        <director>Matt Reeves</director>
        <actor>Robert Pattinson</actor>
    </pelicula>
    
    <pelicula puntuacion="4" anho="2022" clasificacion="NO12" tipo="drama">
        <titulo>The Batman</titulo>
        <duracion>2h 56min</duracion>
        <director>Matt Reeves</director>
        <actor>Robert Pattinson</actor>
        <actor>ZoÃ« Kravitz</actor>
        <actor>Jeffrey Wright</actor>
        <guionista>Matt Reeves</guionista>
        <sinopsis>When the Riddler, a sadistic serial killer, begins murdering key political figures
            in Gotham, Batman is forced to investigate the city's hidden corruption and question his
            family's involvement.</sinopsis>
        <recaudacion euros="200 000 000" />
    </pelicula>
</peliculas>
